#
# Makefile for flash-nandfctrl2
#
# Copyright 2026 Phoenix Systems
#
# SPDX-License-Identifier: BSD-3-Clause
#

OBJS += $(addprefix $(PREFIX_O)devices/flash-nandfctrl2/, data.o nandfctrl2.o meta.o onfi-4.o raw.o)
