#
# Makefile for Phoenix-RTOS loader (ARMv8M HAL stm32)
#
# Copyright 2025 Phoenix Systems
#
# %LICENSE%
#

include hal/armv8m/stm32/n6/Makefile
CFLAGS += -I../plo/hal/armv8m/stm32/n6
OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/stm32/, hal.o)
