#
# Makefile for Phoenix-RTOS loader (ARMv8M HAL mcx)
#
# Copyright 2022, 2024 Phoenix Systems
#
# %LICENSE%
#

include hal/armv8m/mcx/n94x/Makefile
CFLAGS += -Ihal/armv8m/mcx/n94x
OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/mcx/, hal.o)
