#
# Makefile for usbc-cdc
#
# Copyright 2021 Phoenix Systems
#
# %LICENSE%
#

include devices/usbc/Makefile
include devices/usbphy-$(TARGET_SUBFAMILY)/Makefile

OBJS += $(addprefix $(PREFIX_O)devices/usbc-cdc/, cdc.o)
