#
# Makefile for Phoenix-RTOS loader (RISC-V 64 Gaisler HAL)
#
# Copyright 2025 Phoenix Systems
#
# %LICENSE%
#

include hal/$(TARGET_SUFF)/gaisler/$(TARGET_SUBFAMILY)/Makefile

OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/gaisler/, console.o hal.o)
