#
# Makefile for Phoenix-RTOS loader (SPARCV8 LEON HAL)
#
# Copyright 2022 Phoenix Systems
#
# %LICENSE%
#

include hal/sparcv8leon/gaisler/Makefile

OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/, cpu.o string.o interrupts.o exceptions.o _interrupts.o _traps.o)
