#
# Makefile for Phoenix-RTOS loader (ARMv8M HAL nrf)
#
# Copyright 2022 Phoenix Systems
#
# %LICENSE%
#

include hal/armv8m/nrf/91/Makefile
CFLAGS += -I../plo/hal/armv8m/nrf/91
OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/nrf/, hal.o)
