#
# Makefile for Phoenix SBI - extensions
#
# Copyright 2024 Phoenix Systems
#
# %LICENSE%
#

OBJS += $(addprefix $(PREFIX_O)core/extensions/, ecall_base.o ecall_hsm.o ecall_ipi.o ecall_legacy.o ecall_rfence.o \
	ecall_time.o hsm.o ipi.o)
