#
# Makefile for Phoenix-RTOS loader (ARMv7M HAL stm32)
#
# Copyright 2021 Phoenix Systems
#
# %LICENSE%
#

include hal/armv7m/stm32/l4/Makefile
CFLAGS += -Ihal/armv7m/stm32/l4
OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/stm32/, hal.o)
