#
# Makefile for lib
#
# Copyright 2021 Phoenix Systems
#
# %LICENSE%
#

OBJS += $(addprefix $(PREFIX_O)lib/, console.o ctype.o crc32.o cbuffer.o format.o getopt.o list.o log.o printf.o prompt.o sprintf.o strtoul.o)
