#
# Makefile for Phoenix-RTOS loader (SPARCV8 LEON3 HAL)
#
# Copyright 2022 Phoenix Systems
#
# %LICENSE%
#

include hal/sparcv8leon3/gaisler/Makefile

OBJS += $(addprefix $(PREFIX_O)hal/$(TARGET_SUFF)/, string.o interrupts.o exceptions.o _interrupts.o _traps.o)
