#
# Makefile for plo/armv7m7-imxrt106x
#
# Copyright 2020 Phoenix Systems
#
# %LICENSE%
#


OBJS += $(addprefix $(PREFIX_O)$(TARGET)/, _startup.o low.o imxrt.o serial.o board_cmd.o timer.o phfs.o flashdrv.o rom_api.o flashcfg.o flash.o)
